@startuml
title AREA API - authentication flow

== With email/password 2FA inactive ==

Client -> Server : /users/login: Login request (email, password)
alt Valid pair
Server -> Client : 200 (JWT token)
else Invalid pair
Server -> Client : 401
end

== With email/password 2FA active ==

Client -> Server : /users/login: Login request (email, password)
alt Valid pair
Server -> Client : 200 (JWT token that only works on /users/2fa/validate)
Client -> Server : /users/2fa/validate: 2FA validate request (jwt + 2FA code)
    alt Valid 2FA code
    Server -> Client: 200 (JWT token)
    else Invalid 2FA code
    Server -> Client: 400
    else Invalid JWT
    Server -> Client: 401
    end
else Invalid pair
Server -> Client : 401
end

@enduml